SOCP progrming

In [1]:
from cvxopt import matrix, solvers 

In [2]:
f = matrix([-2.0, 1.0, 5.0])
G = [matrix([[12.0, 13.0, 12.0],[6.0, -3.0, -12.0],[-5.0, -5.0, 6.0]]), matrix([[3.0,3.0,-1.0,1.0],[-6.0,-6.0,-9.0,19.0],[10.0,-2.0,-2.0,-3.0]])]
h = [matrix([-12.0,-3.0,-2.0]), matrix([27.0,0.0,3.0,-42])]

In [3]:
sol = solvers.socp(f, Gq=G, hq=h)

     pcost       dcost       gap    pres   dres   k/t
 0:  4.9969e+00 -1.7285e+01  6e+01  3e-01  4e+00  1e+00
 1: -1.6732e+00 -7.0431e+00  1e+01  7e-02  1e+00  6e-01
 2: -1.6221e+01 -3.5417e+01  2e+02  3e-01  5e+00  7e+00
 3: -2.1832e+01 -2.2849e+01  3e+01  4e-02  6e-01  2e+00
 4: -3.5265e+01 -3.5594e+01  1e+01  1e-02  2e-01  9e-01
 5: -3.8303e+01 -3.8314e+01  3e-01  4e-04  6e-03  2e-02
 6: -3.8342e+01 -3.8342e+01  1e-02  1e-05  2e-04  7e-04
 7: -3.8346e+01 -3.8346e+01  9e-04  1e-06  2e-05  7e-05
 8: -3.8346e+01 -3.8346e+01  4e-05  6e-08  9e-07  4e-06
 9: -3.8346e+01 -3.8346e+01  2e-06  3e-09  4e-08  2e-07
Optimal solution found.


In [4]:
print(sol['x'])

[-5.01e+00]
[-5.77e+00]
[-8.52e+00]



--------- QCQP ------------

In [6]:
from scipy.linalg import sqrtm

In [7]:
#-----exapmle---- 
P = matrix([[5,3], [3,4]])
print(P)



[ 5  3]
[ 3  4]



In [8]:
# (1) we need to convert P =A^{T}A
A = sqrtm(P)
print(A)

[[2.10340295 0.75874637]
 [0.75874637 1.85048749]]


In [9]:
import numpy as np
# to cheeck whether A^{T}A gives P
np.matmul(A.T,A)

array([[5., 3.],
       [3., 4.]])

In [10]:
# (2) we need to convert 2A^{T}b from q (given)
# -----------Example ----
q = matrix([1,3])
b = 0.5*np.matmul(np.linalg.inv(A.T),q)
print(b)

[[-0.06418447]
 [ 0.83691446]]
